#!/bin/bash

alias cvb='civibuild'

civibuild_builds_dir() {
  civibuild_install=$(which civibuild)
  civibuild_install=$(dirname "$civibuild_install" 2>/dev/null)
  echo "$civibuild_install/../build"
}

civibuilds() {
  find "$(civibuild_builds_dir)" -maxdepth 1 -type f -exec basename '{}' \; | grep .sh
}

civibuild_show_full() {
  p=$(civibuild_builds_dir)
  build_name="$p/$1.sh"
  pattern="$2"

  if [ $# -gt 1 ]
  then
    grep -i "$pattern" "$build_name"
  else
    cat "$build_name"
  fi
}

civibuild_edit() {
  conf=$(civibuild_builds_dir)/$1.sh
  $EDITOR "$conf"
}

civix_conf_db() {
  conf_path=$1
  if [[ $# -lt 1 ]]; then
    conf_path=$(pwd)
  fi
  conf_path=$(readlink -f "$conf_path")
  pushd $conf_path >/dev/null
  echo "setting civicrm_api3_conf_path to $conf_path"
  civix config:set civicrm_api3_conf_path "$conf_path"
  civix civicrm:ping
  popd
}
