#!/bin/bash

# Laravel

alias art='sail artisan'

# List available network interfaces
if_url() {
	ip addr | awk '/^[0-9]+: / {name=$1; desc=$2} /inet / {sub(/\/[0-9]+/, "", $2); print name, desc, "http://"$2}'
}

# Docker

alias dk=docker
alias dkr='docker run --rm'
alias dkc='docker compose'
alias dki='docker image'
alias dkl='docker ps -a --format '\''table {{if .ID}}{{slice .ID 0 4}}{{end}}\t{{.Names}}\t{{if .Status}}{{slice .Status 0 2}}{{end}}\t{{.Image}}\t{{.Command}}'\'
alias dkll='dkl --no-trunc'
alias dklp="docker ps --format 'table {{if .ID}}{{slice .ID 0 4}}{{end}}\t{{.Names}}\t{{.Ports}}'"


# AWS

alias ecr-token='aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s0z8p6k7'
alias cplt=copilot

# Linode

alias lin-util='linode-cli'
alias lin='linode-cli linodes'

#
# Museum
#

for-every() {
while read line ; do
  read input_line
  `printf "'$1'" "$input_line"`
done
}

svngrep()
{
  grep -r --exclude-dir=.svn --color=auto "$@"
}

svndiff()
{
 svn diff "$@" | colordiff | less -RS
}

killtunnel()
{
  if [ $# == 1 ]; then
    kill_named_ps $1
  else # kill indiscriminately
    kill_named_ps sligotunnel
    kill_named_ps tunnel.ncba
    kill_named_ps frontlinetunnel
    kill_named_ps leonardotunnel
  fi
}

sligo()
{
  nohup ssh sligotunnel -N &
  echo Tunneling Sligo
}

frontline() {
  nohup ssh frontlinetunnel -N > ~/.frontlinetunnel.log 2>&1 &
  echo "Tunneling Frontline Defenders"
  echo "web on: http://localhost:8081/db-gsdev/"
  echo "Use killtunnel to close."
  sleep 5
  read -p "login to web [w] or shell [s] or done [d]?" answer
  case $answer in
    [w]* ) xdg-open http://localhost:8081/db-gsdev/
        echo "opened in default browser."
    ;;
    [s]* ) echo "opening ssh to host - 'frontline'"
       echo "please be patient while I hop around the internet"
       ssh frontline
  esac
}
