#!/bin/bash

# Laravel

alias art='sail artisan'

# List available network interfaces
if_url() {
	ip addr | awk '/^[0-9]+: / {name=$1; desc=$2} /inet / {sub(/\/[0-9]+/, "", $2); print name, desc, "http://"$2}'
}

# Docker

alias dk=docker
alias dkr='docker run --rm'
alias dkc='docker compose'
alias dki='docker image'
alias dkl='docker ps -a --format '\''table {{if .ID}}{{slice .ID 0 4}}{{end}}\t{{.Names}}\t{{if .Status}}{{slice .Status 0 2}}{{end}}\t{{.Image}}\t{{.Command}}'\'
alias dkll='dkl --no-trunc'
alias dklp="docker ps --format 'table {{if .ID}}{{slice .ID 0 4}}{{end}}\t{{.Names}}\t{{.Ports}}'"


# AWS

alias ecr-token='aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s0z8p6k7'
alias cplt=copilot

# Linode

alias lin-util='linode-cli'
alias lin='linode-cli linodes'


# SVN

svngrep()
{
  grep -r --exclude-dir=.svn --color=auto "$@"
}

svndiff()
{
 svn diff "$@" | colordiff | less -RS
}

