#!/bin/bash

# Laravel

alias art='sail artisan'

# List available network interfaces
if_url() {
	ip addr | awk '/^[0-9]+: / {name=$1; desc=$2} /inet / {sub(/\/[0-9]+/, "", $2); print name, desc, "http://"$2}'
}

# Docker

alias dk=docker
alias dkc='docker compose'
alias dki='docker image'

# always remove run containers
alias dkr='docker run --rm'

# Remove all stopped containers
alias dkp='docker container prune'

# custom format; see Go Templates for reference
alias dkl='docker ps -a --format '\''table {{if .ID}}{{slice .ID 0 4}}{{end}}\t{{.Names}}\t{{if .Status}}{{slice .Status 0 2}}{{end}}\t{{.Image}}\t{{.Command}}'\'
# CONT      NAMES                   ST        IMAGE                            COMMAND
# e7b7      website-imagick-1       Ex        dpokidov/imagemagick             "convert" 

# no truncate RUN CMD
alias dkll='dkl --no-trunc'

# display port mappings
alias dklp="docker ps --format 'table {{if .ID}}{{slice .ID 0 4}}{{end}}\t{{.Names}}\t{{.Ports}}'"
# CONT      NAMES                   PORTS
# 7a65      website-httpd-1         0.0.0.0:80->80/tcp, :::80->80/tcp
# b6a0      website-tailwindcss-1   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp

# AWS

alias ecr-token='aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s0z8p6k7'
alias cplt=copilot

# Linode

alias lin-util='linode-cli'
alias lin='linode-cli linodes'


# SVN

svngrep()
{
  grep -r --exclude-dir=.svn --color=auto "$@"
}

svndiff()
{
 svn diff "$@" | colordiff | less -RS
}

