#!/bin/bash

# Laravel

alias art='sail artisan'

# List available network interfaces
if_url() {
	ip addr | awk '/^[0-9]+: / {name=$1; desc=$2} /inet / {sub(/\/[0-9]+/, "", $2); print name, desc, "http://"$2}'
}

# SVN

svngrep()
{
  grep -r --exclude-dir=.svn --color=auto "$@"
}

svndiff()
{
 svn diff "$@" | colordiff | less -RS
}

